import { NicheTemplate } from './types';

export const NICHE_TEMPLATES: NicheTemplate[] = [
  {
    id: 'barbershop',
    name: 'Barbearia Premium',
    niche: 'Barbearia',
    icon: 'Scissors',
    description: 'Sistema completo de agendamentos para barbearias modernas',
    defaultAppName: 'Barbearia Fácil',
    targetAudience: 'Donos de barbearia e salões masculinos',
    mainTask: 'Gerenciar agendamentos online e fidelizar clientes',
    mainBenefit: 'Reduzir faltas, organizar agenda e aumentar faturamento',
    dailyUsers: 'Clientes que agendam serviços e administradores que gerenciam a agenda',
    defaultPages: [
      'Página inicial com serviços',
      'Catálogo de profissionais',
      'Sistema de agendamento',
      'Meus agendamentos',
      'Reagendar/Cancelar',
      'Perfil do cliente',
      'Painel administrativo',
      'Galeria de cortes',
    ],
    suggestedFeatures: [
      'Notificações por WhatsApp',
      'Programa de fidelidade',
      'Galeria de trabalhos',
      'Avaliações de clientes',
      'Lista de espera automática',
      'Integração com Google Calendar',
      'Pagamento online antecipado',
      'Chat com o barbeiro',
    ],
    suggestedColors: {
      primary: '#1a1a2e',
      secondary: '#d4af37',
    },
  },
  {
    id: 'gym',
    name: 'Academia Fitness',
    niche: 'Academia',
    icon: 'Dumbbell',
    description: 'Gestão completa de academia com treinos personalizados',
    defaultAppName: 'Fitness Pro',
    targetAudience: 'Donos de academias e personal trainers',
    mainTask: 'Gerenciar alunos, treinos e mensalidades',
    mainBenefit: 'Automatizar gestão, engajar alunos e reduzir inadimplência',
    dailyUsers: 'Alunos acessando treinos e administradores gerenciando a academia',
    defaultPages: [
      'Dashboard do aluno',
      'Meus treinos',
      'Histórico de treinos',
      'Planos e preços',
      'Agendamento de aulas',
      'Perfil e evolução',
      'Painel administrativo',
      'Gestão de alunos',
    ],
    suggestedFeatures: [
      'Treinos em vídeo',
      'Acompanhamento de evolução',
      'Check-in por QR Code',
      'Controle de acesso',
      'Cobrança automática',
      'Gamificação e desafios',
      'Nutricional integrado',
      'Comunidade de alunos',
    ],
    suggestedColors: {
      primary: '#ef4444',
      secondary: '#f97316',
    },
  },
  {
    id: 'clinic',
    name: 'Clínica Médica',
    niche: 'Saúde',
    icon: 'Stethoscope',
    description: 'Sistema de gestão para clínicas e consultórios',
    defaultAppName: 'Clínica Digital',
    targetAudience: 'Médicos, dentistas e profissionais de saúde',
    mainTask: 'Gerenciar consultas, prontuários e pacientes',
    mainBenefit: 'Otimizar atendimentos e organizar histórico médico',
    dailyUsers: 'Pacientes agendando consultas e profissionais atendendo',
    defaultPages: [
      'Agendamento online',
      'Meus agendamentos',
      'Prontuário eletrônico',
      'Histórico de consultas',
      'Receitas e exames',
      'Perfil do paciente',
      'Painel do médico',
      'Relatórios e métricas',
    ],
    suggestedFeatures: [
      'Teleconsulta integrada',
      'Receita digital',
      'Lembretes automáticos',
      'Prontuário na nuvem',
      'Integração com convênios',
      'Fila de espera virtual',
      'Assinatura digital',
      'LGPD compliance',
    ],
    suggestedColors: {
      primary: '#0ea5e9',
      secondary: '#14b8a6',
    },
  },
  {
    id: 'restaurant',
    name: 'Restaurante & Delivery',
    niche: 'Alimentação',
    icon: 'UtensilsCrossed',
    description: 'Cardápio digital e sistema de pedidos completo',
    defaultAppName: 'Sabor Express',
    targetAudience: 'Donos de restaurantes, lanchonetes e food trucks',
    mainTask: 'Gerenciar pedidos, cardápio e entregas',
    mainBenefit: 'Aumentar vendas e reduzir taxas de marketplaces',
    dailyUsers: 'Clientes fazendo pedidos e funcionários gerenciando',
    defaultPages: [
      'Cardápio digital',
      'Carrinho de compras',
      'Checkout e pagamento',
      'Acompanhar pedido',
      'Histórico de pedidos',
      'Perfil e endereços',
      'Painel de pedidos',
      'Gestão de cardápio',
    ],
    suggestedFeatures: [
      'Pedidos pelo WhatsApp',
      'Rastreamento em tempo real',
      'Cupons de desconto',
      'Programa de fidelidade',
      'Múltiplas formas de pagamento',
      'Gestão de motoboys',
      'Integração com impressora',
      'Reserva de mesas',
    ],
    suggestedColors: {
      primary: '#ea580c',
      secondary: '#fbbf24',
    },
  },
  {
    id: 'realestate',
    name: 'Imobiliária',
    niche: 'Imobiliário',
    icon: 'Home',
    description: 'Portal de imóveis com gestão de corretores',
    defaultAppName: 'Imóveis Pro',
    targetAudience: 'Imobiliárias e corretores de imóveis',
    mainTask: 'Divulgar imóveis e gerenciar leads',
    mainBenefit: 'Captar mais clientes e fechar mais negócios',
    dailyUsers: 'Clientes buscando imóveis e corretores prospectando',
    defaultPages: [
      'Busca de imóveis',
      'Detalhes do imóvel',
      'Galeria de fotos',
      'Agendar visita',
      'Simulador de financiamento',
      'Favoritos',
      'Painel do corretor',
      'Gestão de leads',
    ],
    suggestedFeatures: [
      'Tour virtual 360°',
      'Filtros avançados',
      'Mapa interativo',
      'Chat com corretor',
      'Comparador de imóveis',
      'Integração com portais',
      'CRM integrado',
      'Documentação digital',
    ],
    suggestedColors: {
      primary: '#059669',
      secondary: '#0d9488',
    },
  },
  {
    id: 'school',
    name: 'Escola & Cursos',
    niche: 'Educação',
    icon: 'GraduationCap',
    description: 'Plataforma de ensino e gestão escolar',
    defaultAppName: 'EduClass',
    targetAudience: 'Escolas, cursos e infoprodutores',
    mainTask: 'Gerenciar alunos, aulas e conteúdos',
    mainBenefit: 'Escalar o ensino e engajar alunos',
    dailyUsers: 'Alunos assistindo aulas e professores criando conteúdo',
    defaultPages: [
      'Área do aluno',
      'Minhas aulas',
      'Player de vídeo',
      'Material de apoio',
      'Provas e exercícios',
      'Certificados',
      'Painel do professor',
      'Gestão de turmas',
    ],
    suggestedFeatures: [
      'Aulas ao vivo',
      'Fórum de dúvidas',
      'Gamificação',
      'Emissão de certificado',
      'Controle de progresso',
      'Quizzes interativos',
      'Integração com Zoom',
      'App mobile',
    ],
    suggestedColors: {
      primary: '#7c3aed',
      secondary: '#a855f7',
    },
  },
  {
    id: 'petshop',
    name: 'Pet Shop',
    niche: 'Pet',
    icon: 'PawPrint',
    description: 'Sistema completo para pet shops e clínicas veterinárias',
    defaultAppName: 'Pet Care',
    targetAudience: 'Donos de pet shops e clínicas veterinárias',
    mainTask: 'Gerenciar serviços, vendas e consultas de pets',
    mainBenefit: 'Fidelizar tutores e organizar atendimentos',
    dailyUsers: 'Tutores de pets e funcionários da loja',
    defaultPages: [
      'Agendamento de banho/tosa',
      'Loja online',
      'Consultas veterinárias',
      'Perfil do pet',
      'Histórico de vacinas',
      'Carrinho de compras',
      'Painel administrativo',
      'Gestão de estoque',
    ],
    suggestedFeatures: [
      'Lembretes de vacinas',
      'Planos de assinatura',
      'Delivery de ração',
      'Prontuário do pet',
      'Galeria de fotos',
      'Táxi dog integrado',
      'Programa de fidelidade',
      'Prescrição veterinária',
    ],
    suggestedColors: {
      primary: '#f59e0b',
      secondary: '#84cc16',
    },
  },
  {
    id: 'lawyer',
    name: 'Escritório de Advocacia',
    niche: 'Jurídico',
    icon: 'Scale',
    description: 'Gestão de processos e atendimento a clientes',
    defaultAppName: 'JurisControl',
    targetAudience: 'Advogados e escritórios de advocacia',
    mainTask: 'Gerenciar processos, prazos e clientes',
    mainBenefit: 'Nunca perder prazos e organizar todos os processos',
    dailyUsers: 'Advogados, estagiários e clientes',
    defaultPages: [
      'Dashboard de processos',
      'Agenda de audiências',
      'Gestão de prazos',
      'Área do cliente',
      'Documentos do processo',
      'Financeiro',
      'Relatórios',
      'Biblioteca jurídica',
    ],
    suggestedFeatures: [
      'Alertas de prazos',
      'Integração tribunais',
      'Assinatura digital',
      'Timesheet automático',
      'Honorários e custas',
      'Portal do cliente',
      'Templates de peças',
      'IA para pesquisa',
    ],
    suggestedColors: {
      primary: '#1e293b',
      secondary: '#475569',
    },
  },
  {
    id: 'beauty',
    name: 'Salão de Beleza',
    niche: 'Beleza',
    icon: 'Sparkles',
    description: 'Agendamento e gestão para salões de beleza',
    defaultAppName: 'Beauty Book',
    targetAudience: 'Donos de salões de beleza e estúdios',
    mainTask: 'Gerenciar agendamentos e serviços de beleza',
    mainBenefit: 'Agenda sempre cheia e clientes satisfeitos',
    dailyUsers: 'Clientes agendando e profissionais atendendo',
    defaultPages: [
      'Catálogo de serviços',
      'Agendamento online',
      'Escolha de profissional',
      'Meus agendamentos',
      'Galeria de trabalhos',
      'Perfil da cliente',
      'Painel de gestão',
      'Comissões',
    ],
    suggestedFeatures: [
      'Portfólio de trabalhos',
      'Pacotes de serviços',
      'Programa de indicação',
      'Lembretes automáticos',
      'Controle de comissões',
      'Estoque de produtos',
      'Venda de produtos',
      'Planos de fidelidade',
    ],
    suggestedColors: {
      primary: '#ec4899',
      secondary: '#f472b6',
    },
  },
  {
    id: 'contractor',
    name: 'Prestador de Serviços',
    niche: 'Serviços',
    icon: 'Wrench',
    description: 'Orçamentos e gestão para prestadores de serviços',
    defaultAppName: 'Serviço Pro',
    targetAudience: 'Eletricistas, encanadores, pintores e afins',
    mainTask: 'Gerenciar orçamentos, serviços e clientes',
    mainBenefit: 'Profissionalizar o negócio e conquistar mais clientes',
    dailyUsers: 'Clientes solicitando serviços e profissionais atendendo',
    defaultPages: [
      'Solicitar orçamento',
      'Catálogo de serviços',
      'Meus orçamentos',
      'Acompanhar serviço',
      'Histórico',
      'Avaliações',
      'Painel do profissional',
      'Agenda de serviços',
    ],
    suggestedFeatures: [
      'Orçamento automático',
      'Fotos antes/depois',
      'GPS de localização',
      'Chat com cliente',
      'Garantia de serviço',
      'Múltiplos orçamentos',
      'Recorrência de serviços',
      'Nota fiscal integrada',
    ],
    suggestedColors: {
      primary: '#2563eb',
      secondary: '#3b82f6',
    },
  },
];
