import { NicheTemplate } from './types';

export const NICHE_TEMPLATES: NicheTemplate[] = [
  {
    id: 'barbershop',
    name: 'Barbearia Premium',
    niche: 'Barbearia',
    icon: 'Scissors',
    description: 'Sistema completo de agendamentos para barbearias modernas com gestão de profissionais, fidelidade e pagamentos',
    defaultAppName: 'BarberPro',
    targetAudience: 'Donos de barbearias e salões masculinos que desejam modernizar o atendimento, reduzir faltas e aumentar o faturamento através de uma experiência digital completa para seus clientes',
    mainTask: 'Permitir que clientes agendem cortes de cabelo, barba e outros serviços diretamente pelo celular, visualizando horários disponíveis de cada barbeiro, preços e tempo estimado de cada serviço. O sistema gerencia automaticamente a agenda de múltiplos profissionais, envia lembretes via WhatsApp, cobra sinal antecipado para reduzir no-shows e permite reagendamento/cancelamento seguindo regras configuráveis',
    mainBenefit: 'Eliminar agendamentos por telefone e WhatsApp manual, reduzir faltas em até 70% com lembretes automáticos e cobrança de sinal, organizar a agenda de vários barbeiros em um único painel centralizado, e fidelizar clientes através de programa de pontos e histórico de cortes',
    dailyUsers: 'Clientes finais que agendam e pagam pelo app, barbeiros que visualizam sua agenda e marcam atendimentos como concluídos, e administradores que gerenciam a barbearia, preços, horários e relatórios financeiros',
    businessModel: 'Agendamento online com cobrança de sinal (10-30% do valor) para garantir a reserva. Comissão por barbeiro configurável. Programa de fidelidade onde a cada X cortes o cliente ganha um grátis ou desconto',
    mainProblem: 'Barbearias perdem até 30% do faturamento com no-shows, gastam horas atendendo WhatsApp para agendar, não têm visibilidade da agenda de todos os barbeiros, e não conseguem fidelizar clientes de forma sistemática',
    expectedOutcome: 'Dashboard mostrando agenda do dia por barbeiro, taxa de ocupação, faturamento previsto vs realizado, clientes que mais frequentam, e alertas de horários vagos que podem ser preenchidos',
    defaultPages: [
      'Página inicial com serviços em destaque e CTAs',
      'Catálogo de serviços com preços e duração',
      'Lista de barbeiros com foto, especialidades e avaliação',
      'Calendário de agendamento com horários disponíveis',
      'Checkout com seleção de pagamento (PIX/Cartão)',
      'Confirmação de agendamento com QR Code',
      'Meus Agendamentos (próximos e histórico)',
      'Perfil do cliente com pontos de fidelidade',
      'Galeria de cortes e estilos',
      'Painel Admin - Dashboard',
      'Painel Admin - Gestão de Barbeiros',
      'Painel Admin - Configurações e Preços',
      'Painel Admin - Relatórios Financeiros',
    ],
    suggestedFeatures: [
      'Notificações automáticas via WhatsApp',
      'Programa de fidelidade com pontos',
      'Lista de espera inteligente',
      'Galeria de trabalhos por barbeiro',
      'Avaliações e reviews de clientes',
      'Integração com Google Calendar',
      'Pagamento online antecipado (sinal)',
      'Chat direto com o barbeiro',
      'Cancelamento com multa configurável',
      'Reagendamento em 1 clique',
      'Check-in via QR Code',
      'Histórico de cortes do cliente',
    ],
    coreFeatures: [
      'Agendamento online em tempo real',
      'Gestão de múltiplos profissionais',
      'Controle de agenda por barbeiro',
      'Cobrança de sinal online',
      'Lembretes automáticos',
      'Painel administrativo completo',
      'Relatórios de faturamento',
      'Gestão de serviços e preços',
    ],
    integrations: [
      'WhatsApp Business API para notificações',
      'Stripe ou Mercado Pago para pagamentos',
      'Google Calendar para sincronização',
      'Evolution API para mensagens automatizadas',
    ],
    userFlows: [
      'Cliente abre o app → Vê serviços → Escolhe barbeiro → Seleciona horário → Paga sinal → Recebe confirmação → Lembrete no dia → Check-in → Avalia',
      'Admin acessa painel → Vê agenda do dia → Marca cliente como atendido → Visualiza faturamento → Exporta relatório',
    ],
    suggestedColors: {
      primary: '#1a1a2e',
      secondary: '#d4af37',
      accent: '#c9a227',
      background: '#0f0f1a',
    },
    designStyle: 'modern',
    iconStyle: 'lucide',
  },
  {
    id: 'gym',
    name: 'Academia Fitness',
    niche: 'Academia',
    icon: 'Dumbbell',
    description: 'Gestão completa de academia com treinos personalizados, controle de acesso e acompanhamento de evolução',
    defaultAppName: 'FitnessPro',
    targetAudience: 'Donos de academias, estúdios de musculação e personal trainers que precisam gerenciar alunos, controlar mensalidades, disponibilizar treinos personalizados e acompanhar a evolução física de cada membro',
    mainTask: 'Permitir que alunos acessem seus treinos personalizados pelo celular, registrem execuções, acompanhem sua evolução com fotos e medidas, façam check-in na academia via QR Code, e mantenham o pagamento da mensalidade em dia. Para gestores, controlar acessos, inadimplência, e performance dos personal trainers',
    mainBenefit: 'Acabar com as fichas de papel, automatizar cobranças recorrentes reduzindo inadimplência em até 50%, engajar alunos com gamificação e desafios, e permitir que personal trainers atendam mais alunos com treinos digitais personalizados',
    dailyUsers: 'Alunos acessando treinos e registrando execuções, personal trainers montando e acompanhando treinos de seus alunos, recepcionistas controlando acessos, e gestores analisando métricas do negócio',
    businessModel: 'Assinatura mensal ou anual dos alunos. Comissão ou salário para personal trainers. Venda de serviços adicionais (avaliação física, nutricionista). Cobrança automática no cartão',
    mainProblem: 'Academias perdem alunos por falta de engajamento e acompanhamento, gastam tempo com cobranças manuais, não conseguem escalar personal trainers, e não têm dados sobre frequência e evolução dos alunos',
    expectedOutcome: 'Dashboard com total de alunos ativos, taxa de retenção, inadimplência, check-ins por dia, alunos que não vêm há X dias, e ranking de engajamento',
    defaultPages: [
      'Tela de login do aluno',
      'Dashboard do aluno com resumo',
      'Meu Treino do dia',
      'Biblioteca de exercícios com vídeos',
      'Histórico de treinos realizados',
      'Evolução física (fotos e medidas)',
      'Planos e pagamentos',
      'Check-in via QR Code',
      'Perfil do aluno',
      'Painel do Personal - Meus Alunos',
      'Painel do Personal - Montar Treino',
      'Painel Admin - Dashboard',
      'Painel Admin - Gestão de Alunos',
      'Painel Admin - Controle de Acesso',
      'Painel Admin - Financeiro',
    ],
    suggestedFeatures: [
      'Treinos em vídeo demonstrativo',
      'Acompanhamento de evolução com gráficos',
      'Check-in por QR Code na catraca',
      'Controle de acesso por horário',
      'Cobrança automática recorrente',
      'Gamificação com desafios e rankings',
      'Área nutricional integrada',
      'Comunidade e grupos de alunos',
      'Notificações de treino do dia',
      'Avaliação física digital',
      'Chat aluno-personal',
      'Metas e conquistas',
    ],
    coreFeatures: [
      'Treinos personalizados digitais',
      'Controle de acesso',
      'Gestão de mensalidades',
      'Check-in digital',
      'Acompanhamento de evolução',
      'Painel para personal trainers',
      'Cobrança automática',
      'Relatórios gerenciais',
    ],
    integrations: [
      'Gateway de pagamento para recorrência',
      'Catracas e controle de acesso',
      'WhatsApp para notificações',
      'App de nutrição (opcional)',
    ],
    userFlows: [
      'Aluno faz login → Vê treino do dia → Inicia treino → Registra séries → Finaliza → Vê progresso',
      'Personal acessa painel → Seleciona aluno → Monta treino → Aluno recebe notificação',
    ],
    suggestedColors: {
      primary: '#ef4444',
      secondary: '#f97316',
      accent: '#fbbf24',
      background: '#18181b',
    },
    designStyle: 'modern',
    iconStyle: 'lucide',
  },
  {
    id: 'clinic',
    name: 'Clínica Médica',
    niche: 'Saúde',
    icon: 'Stethoscope',
    description: 'Sistema de gestão para clínicas e consultórios com prontuário eletrônico, agendamentos e teleconsulta',
    defaultAppName: 'ClínicaDigital',
    targetAudience: 'Médicos, dentistas, psicólogos e outros profissionais de saúde que precisam gerenciar consultas, manter prontuários eletrônicos seguros, oferecer teleconsulta e organizar o fluxo de atendimento da clínica',
    mainTask: 'Permitir que pacientes agendem consultas online visualizando a disponibilidade de cada profissional, preencham fichas de anamnese antes da consulta, recebam lembretes, façam teleconsulta quando aplicável, e acessem suas receitas e exames digitalmente. Para profissionais, ter prontuário eletrônico completo, prescrição digital com assinatura, e agenda organizada',
    mainBenefit: 'Eliminar papel e fichas físicas com prontuário 100% digital e seguro (LGPD), reduzir faltas com confirmação e lembretes, aumentar receita oferecendo teleconsulta, e profissionalizar o atendimento com experiência digital moderna para o paciente',
    dailyUsers: 'Pacientes agendando consultas e acessando histórico, médicos/profissionais atendendo e prescrevendo, recepcionistas gerenciando agenda e confirmações, e gestores analisando métricas da clínica',
    businessModel: 'Consultas particulares ou convênio. Teleconsulta com pagamento antecipado. Pacotes de consultas com desconto. Retorno gratuito em X dias',
    mainProblem: 'Clínicas perdem tempo com agendamentos manuais, prontuários de papel são desorganizados e inseguros, não oferecem teleconsulta, e pacientes faltam por esquecer',
    expectedOutcome: 'Dashboard com consultas do dia, taxa de comparecimento, faturamento por profissional, novos vs retornos, e tempo médio de espera',
    defaultPages: [
      'Agendamento online de consultas',
      'Seleção de especialidade e profissional',
      'Calendário de horários disponíveis',
      'Ficha de anamnese pré-consulta',
      'Meus Agendamentos',
      'Histórico de consultas',
      'Minhas receitas e exames',
      'Área de teleconsulta (videoconferência)',
      'Perfil do paciente',
      'Painel Médico - Agenda do dia',
      'Painel Médico - Prontuário do paciente',
      'Painel Médico - Prescrição digital',
      'Painel Admin - Dashboard',
      'Painel Admin - Gestão de profissionais',
      'Painel Admin - Relatórios',
    ],
    suggestedFeatures: [
      'Teleconsulta com videoconferência',
      'Receita digital com QR Code',
      'Lembretes automáticos de consulta',
      'Prontuário eletrônico (LGPD)',
      'Integração com convênios',
      'Fila de espera virtual',
      'Assinatura digital de documentos',
      'Anamnese digital pré-consulta',
      'Encaminhamento entre especialidades',
      'Histórico médico completo',
      'Exames e anexos digitais',
      'Chat seguro médico-paciente',
    ],
    coreFeatures: [
      'Agendamento online',
      'Prontuário eletrônico',
      'Prescrição digital',
      'Teleconsulta',
      'Gestão de profissionais',
      'Lembretes automáticos',
      'Histórico do paciente',
      'Relatórios clínicos',
    ],
    integrations: [
      'Gateway de pagamento',
      'WhatsApp para lembretes',
      'Videoconferência (Daily/Whereby)',
      'ICP-Brasil para assinatura digital',
    ],
    userFlows: [
      'Paciente agenda → Preenche anamnese → Recebe lembrete → Faz consulta → Recebe receita digital → Acessa histórico',
      'Médico vê agenda → Acessa prontuário → Atende → Prescreve → Salva no prontuário',
    ],
    suggestedColors: {
      primary: '#0ea5e9',
      secondary: '#14b8a6',
      accent: '#06b6d4',
      background: '#f8fafc',
    },
    designStyle: 'minimal',
    iconStyle: 'lucide',
  },
  {
    id: 'restaurant',
    name: 'Restaurante & Delivery',
    niche: 'Alimentação',
    icon: 'UtensilsCrossed',
    description: 'Cardápio digital e sistema de pedidos próprio para restaurantes, lanchonetes e delivery',
    defaultAppName: 'SaborExpress',
    targetAudience: 'Donos de restaurantes, lanchonetes, pizzarias e food trucks que querem ter seu próprio canal de pedidos online sem depender de iFood e Rappi, mantendo 100% da margem e relacionamento direto com o cliente',
    mainTask: 'Permitir que clientes visualizem o cardápio digital com fotos e descrições, montem seu pedido com personalizações (adicionar, remover ingredientes), escolham entre delivery ou retirada, paguem online (PIX, cartão) e acompanhem em tempo real o status do pedido. Para o restaurante, gerenciar pedidos em tempo real, controlar cardápio e estoque, e ter visão do faturamento',
    mainBenefit: 'Eliminar taxas de até 27% dos marketplaces, ter canal próprio de vendas com dados dos clientes, fidelizar através de cupons e programa de pontos, e automatizar a operação de pedidos reduzindo erros',
    dailyUsers: 'Clientes fazendo pedidos pelo celular, cozinha recebendo e preparando pedidos, motoboys visualizando entregas, caixa conferindo pagamentos, e gestor analisando vendas e cardápio',
    businessModel: 'Venda direta sem intermediários. Taxa de entrega configurável. Pedido mínimo. Cupons de desconto para primeira compra e fidelização',
    mainProblem: 'Restaurantes pagam até 27% de comissão para marketplaces, não têm dados dos próprios clientes, dependem 100% de terceiros, e perdem margem que poderia ser lucro',
    expectedOutcome: 'Dashboard com pedidos em andamento, faturamento do dia, ticket médio, pratos mais vendidos, taxa de recompra, e mapa de entregas',
    defaultPages: [
      'Página inicial com destaques e promoções',
      'Cardápio digital por categoria',
      'Página do produto com personalizações',
      'Carrinho de compras',
      'Checkout com endereço e pagamento',
      'Acompanhamento do pedido em tempo real',
      'Histórico de pedidos',
      'Perfil com endereços salvos',
      'Cupons e promoções',
      'Programa de fidelidade',
      'Painel Cozinha - Pedidos em preparo',
      'Painel Admin - Dashboard',
      'Painel Admin - Gestão de Cardápio',
      'Painel Admin - Pedidos',
      'Painel Admin - Entregas',
      'Painel Admin - Cupons e Promoções',
    ],
    suggestedFeatures: [
      'Cardápio digital com fotos',
      'Pedidos via WhatsApp integrado',
      'Rastreamento de entrega em tempo real',
      'Cupons de desconto e promoções',
      'Programa de fidelidade',
      'Múltiplas formas de pagamento',
      'Gestão de motoboys',
      'Integração com impressora térmica',
      'Reserva de mesas',
      'Avaliação de pedidos',
      'Repetir pedido anterior',
      'Tempo estimado de entrega',
    ],
    coreFeatures: [
      'Cardápio digital responsivo',
      'Sistema de pedidos online',
      'Pagamento integrado',
      'Acompanhamento em tempo real',
      'Gestão de entregas',
      'Painel da cozinha',
      'Cupons e promoções',
      'Relatórios de vendas',
    ],
    integrations: [
      'Gateway de pagamento (PIX e cartão)',
      'WhatsApp para notificações',
      'Impressora térmica',
      'Google Maps para entregas',
    ],
    userFlows: [
      'Cliente acessa → Monta pedido → Finaliza carrinho → Paga → Acompanha status → Recebe → Avalia',
      'Pedido chega → Cozinha aceita → Prepara → Pronto → Motoboy coleta → Entrega → Finalizado',
    ],
    suggestedColors: {
      primary: '#ea580c',
      secondary: '#fbbf24',
      accent: '#f97316',
      background: '#fffbeb',
    },
    designStyle: 'modern',
    iconStyle: 'lucide',
  },
  {
    id: 'realestate',
    name: 'Imobiliária',
    niche: 'Imobiliário',
    icon: 'Home',
    description: 'Portal de imóveis completo com busca avançada, tour virtual e gestão de leads para corretores',
    defaultAppName: 'ImóveisPro',
    targetAudience: 'Imobiliárias e corretores de imóveis autônomos que precisam divulgar imóveis de forma profissional, captar leads qualificados, agendar visitas e acompanhar todo o funil de vendas até o fechamento',
    mainTask: 'Permitir que clientes busquem imóveis com filtros avançados (localização, preço, tipo, quartos), visualizem fotos em alta qualidade e tour virtual 360°, agendem visitas com corretores, e simulem financiamento. Para corretores, gerenciar carteira de imóveis, captar e nutrir leads, e acompanhar negociações em CRM integrado',
    mainBenefit: 'Ter presença digital profissional que funciona 24h captando leads, diferenciar-se com tour virtual que elimina visitas improdutivas, automatizar follow-up com leads, e ter visibilidade completa do funil de vendas',
    dailyUsers: 'Clientes buscando imóveis para comprar ou alugar, corretores gerenciando seus leads e imóveis, fotógrafos fazendo upload de mídias, e gestores analisando performance da equipe',
    businessModel: 'Comissão sobre vendas e locações. Destaque de imóveis no topo. Planos para corretores autônomos',
    mainProblem: 'Imobiliárias dependem de portais caros (ZAP, Viva Real), perdem leads por demora no atendimento, fazem visitas improdutivas, e não têm CRM integrado',
    expectedOutcome: 'Dashboard com leads novos, imóveis ativos, visitas agendadas, propostas em negociação, e vendas fechadas no mês',
    defaultPages: [
      'Página inicial com busca e destaques',
      'Busca avançada com filtros',
      'Lista de imóveis com cards',
      'Página do imóvel com galeria e tour 360°',
      'Agendar visita',
      'Simulador de financiamento',
      'Favoritos do cliente',
      'Perfil do cliente',
      'Painel Corretor - Meus Leads',
      'Painel Corretor - Meus Imóveis',
      'Painel Corretor - Agenda de Visitas',
      'Painel Admin - Dashboard',
      'Painel Admin - Gestão de Corretores',
      'Painel Admin - Relatórios',
    ],
    suggestedFeatures: [
      'Tour virtual 360°',
      'Filtros avançados de busca',
      'Mapa interativo de localização',
      'Chat com corretor',
      'Comparador de imóveis',
      'Simulador de financiamento',
      'CRM integrado para corretores',
      'Documentação digital',
      'Integração com portais',
      'Avaliação de imóveis',
      'Notificações de imóveis novos',
      'Compartilhar imóvel',
    ],
    coreFeatures: [
      'Catálogo de imóveis',
      'Busca com filtros',
      'Galeria de fotos',
      'Agendamento de visitas',
      'Gestão de leads',
      'Painel do corretor',
      'Simulador financeiro',
      'Relatórios de vendas',
    ],
    integrations: [
      'Google Maps para localização',
      'WhatsApp para contato',
      'Portais imobiliários (API)',
      'Bancos para simulação',
    ],
    userFlows: [
      'Cliente busca → Filtra → Vê imóvel → Agenda visita → Corretor confirma → Visita → Proposta → Fechamento',
      'Corretor cadastra imóvel → Publica → Lead chega → Atende → Agenda visita → Negociação',
    ],
    suggestedColors: {
      primary: '#059669',
      secondary: '#0d9488',
      accent: '#10b981',
      background: '#f0fdf4',
    },
    designStyle: 'corporate',
    iconStyle: 'lucide',
  },
  {
    id: 'school',
    name: 'Escola & Cursos',
    niche: 'Educação',
    icon: 'GraduationCap',
    description: 'Plataforma de ensino online (EAD) com videoaulas, exercícios, certificados e gamificação',
    defaultAppName: 'EduClass',
    targetAudience: 'Escolas, cursos profissionalizantes, infoprodutores e educadores que querem oferecer cursos online, gerenciar alunos, acompanhar progresso e escalar o ensino sem limites físicos',
    mainTask: 'Permitir que alunos assistam videoaulas organizadas em módulos, façam exercícios e provas, acompanhem seu progresso, participem de fóruns de discussão, e recebam certificados ao concluir. Para instrutores, criar e organizar conteúdo, corrigir atividades, e acompanhar engajamento dos alunos',
    mainBenefit: 'Escalar o ensino para milhares de alunos com o mesmo esforço, ter plataforma própria sem depender de marketplaces que cobram até 50%, engajar alunos com gamificação e certificados, e ter dados completos de consumo do conteúdo',
    dailyUsers: 'Alunos consumindo conteúdo e fazendo exercícios, professores criando aulas e corrigindo, tutores respondendo dúvidas, e gestores analisando métricas de engajamento',
    businessModel: 'Venda de cursos individuais ou assinatura. Planos mensais/anuais. Cursos gratuitos com certificado pago',
    mainProblem: 'Educadores perdem até 50% para plataformas como Hotmart/Udemy, não têm controle dos dados dos alunos, e não conseguem personalizar a experiência',
    expectedOutcome: 'Dashboard com alunos ativos, cursos mais assistidos, taxa de conclusão, engajamento por módulo, e faturamento',
    defaultPages: [
      'Catálogo de cursos',
      'Página do curso com módulos',
      'Player de vídeo com progresso',
      'Material de apoio (PDFs)',
      'Exercícios e quizzes',
      'Fórum de dúvidas',
      'Meu progresso e certificados',
      'Perfil do aluno',
      'Área de pagamento',
      'Painel Professor - Meus Cursos',
      'Painel Professor - Criar Conteúdo',
      'Painel Professor - Alunos',
      'Painel Admin - Dashboard',
      'Painel Admin - Gestão de Cursos',
      'Painel Admin - Financeiro',
    ],
    suggestedFeatures: [
      'Videoaulas com player customizado',
      'Quizzes e exercícios interativos',
      'Fórum de dúvidas por curso',
      'Certificados automáticos',
      'Gamificação com pontos e badges',
      'Aulas ao vivo integradas',
      'Controle de progresso detalhado',
      'App mobile (PWA)',
      'Comunidade de alunos',
      'Download de material offline',
      'Área de membros',
      'Integrações de pagamento',
    ],
    coreFeatures: [
      'Player de vídeo',
      'Organização em módulos',
      'Sistema de exercícios',
      'Controle de progresso',
      'Certificados digitais',
      'Fórum de dúvidas',
      'Gestão de alunos',
      'Cobrança e assinaturas',
    ],
    integrations: [
      'Vimeo/YouTube para vídeos',
      'Stripe para pagamentos',
      'Zoom para lives',
      'Email marketing',
    ],
    userFlows: [
      'Aluno compra curso → Acessa área → Assiste aula → Faz exercício → Avança módulo → Conclui → Recebe certificado',
      'Professor cria módulo → Faz upload de vídeo → Adiciona exercícios → Publica → Acompanha engajamento',
    ],
    suggestedColors: {
      primary: '#7c3aed',
      secondary: '#a855f7',
      accent: '#8b5cf6',
      background: '#faf5ff',
    },
    designStyle: 'modern',
    iconStyle: 'lucide',
  },
  {
    id: 'petshop',
    name: 'Pet Shop',
    niche: 'Pet',
    icon: 'PawPrint',
    description: 'Sistema completo para pet shops com agendamento de banho, loja online e prontuário veterinário',
    defaultAppName: 'PetCare',
    targetAudience: 'Donos de pet shops, clínicas veterinárias e banho & tosa que precisam gerenciar agendamentos, vender produtos, manter histórico de cada pet e fidelizar tutores',
    mainTask: 'Permitir que tutores agendem serviços de banho, tosa e consultas veterinárias, comprem produtos (ração, medicamentos) com delivery, visualizem o histórico e cartão de vacinas do pet, e recebam lembretes de vacinação e vermifugação. Para o negócio, gerenciar a agenda de groomers e veterinários, controlar estoque, e manter prontuário de cada animal',
    mainBenefit: 'Centralizar tudo do pet em um app só (serviços + loja + saúde), fidelizar tutores com lembretes automáticos, aumentar ticket médio com sugestões de produtos, e profissionalizar o atendimento com prontuário digital',
    dailyUsers: 'Tutores agendando serviços e comprando produtos, groomers (tosadores) visualizando agenda do dia, veterinários acessando prontuários, e gestores controlando operação',
    businessModel: 'Serviços de estética e veterinário. Venda de produtos. Planos de assinatura de ração. Pacotes de banho com desconto',
    mainProblem: 'Pet shops perdem clientes por não lembrar data de vacinas/banho, não têm histórico organizado de cada pet, e vendem apenas no balcão sem canal digital',
    expectedOutcome: 'Dashboard com agendamentos do dia, pets que precisam de vacina, vendas de produtos, e clientes para reativar',
    defaultPages: [
      'Página inicial com serviços',
      'Meus Pets (cadastro e perfil)',
      'Agendamento de serviços',
      'Loja de produtos',
      'Carrinho e checkout',
      'Histórico de vacinas e consultas',
      'Meus Agendamentos',
      'Meus Pedidos',
      'Perfil do tutor',
      'Painel Groomer - Agenda',
      'Painel Vet - Prontuário',
      'Painel Admin - Dashboard',
      'Painel Admin - Gestão de Pets',
      'Painel Admin - Estoque',
    ],
    suggestedFeatures: [
      'Lembretes de vacinas e vermífugos',
      'Planos de assinatura de ração',
      'Delivery de produtos',
      'Prontuário veterinário digital',
      'Galeria de fotos do pet',
      'Táxi dog integrado',
      'Programa de fidelidade',
      'Prescrição veterinária digital',
      'QR Code para identificação',
      'Chat com veterinário',
      'Tracking de entrega',
      'Avaliação de serviços',
    ],
    coreFeatures: [
      'Cadastro de pets',
      'Agendamento de serviços',
      'Loja de produtos',
      'Prontuário veterinário',
      'Histórico de vacinas',
      'Lembretes automáticos',
      'Gestão de estoque',
      'Entregas',
    ],
    integrations: [
      'WhatsApp para lembretes',
      'Gateway de pagamento',
      'Sistema de entregas',
      'Impressora térmica',
    ],
    userFlows: [
      'Tutor cadastra pet → Agenda banho → Paga → Leva o pet → Busca → Recebe fotos → Avalia',
      'Vet atende → Registra no prontuário → Prescreve → Sistema agenda próxima vacina → Tutor recebe lembrete',
    ],
    suggestedColors: {
      primary: '#f59e0b',
      secondary: '#84cc16',
      accent: '#fbbf24',
      background: '#fefce8',
    },
    designStyle: 'modern',
    iconStyle: 'phosphor',
  },
  {
    id: 'lawyer',
    name: 'Escritório de Advocacia',
    niche: 'Jurídico',
    icon: 'Scale',
    description: 'Gestão de processos, prazos, atendimento ao cliente e honorários para advogados',
    defaultAppName: 'JurisControl',
    targetAudience: 'Advogados, escritórios de advocacia e departamentos jurídicos que precisam gerenciar processos, controlar prazos fatais, atender clientes e controlar honorários',
    mainTask: 'Permitir que advogados cadastrem e acompanhem todos os seus processos, recebam alertas de prazos fatais, tenham acesso rápido a documentos e peças, controlem horas trabalhadas (timesheet), e mantenham clientes informados através de portal exclusivo. Integração com tribunais para atualização automática de andamentos',
    mainBenefit: 'Nunca mais perder um prazo fatal, ter todos os processos e documentos organizados em um só lugar, automatizar comunicação com cliente sobre andamentos, e ter controle financeiro de honorários e custas',
    dailyUsers: 'Advogados consultando processos e prazos, estagiários fazendo pesquisas e apoio, secretária controlando agenda, clientes acompanhando seus casos, e sócios analisando produtividade e faturamento',
    businessModel: 'Honorários advocatícios (fixo ou êxito). Cobrança por hora trabalhada. Pacotes de consultoria. Custas processuais repassadas',
    mainProblem: 'Escritórios perdem prazos por falta de controle, gastam horas procurando documentos, não têm visibilidade de produtividade, e clientes reclamam de falta de informação',
    expectedOutcome: 'Dashboard com prazos da semana, processos por fase, produtividade por advogado, honorários a receber, e casos próximos de prescrição',
    defaultPages: [
      'Dashboard com prazos urgentes',
      'Lista de processos',
      'Detalhes do processo com timeline',
      'Agenda de audiências e compromissos',
      'Gestão de prazos',
      'Documentos e peças',
      'Portal do Cliente',
      'Timesheet (controle de horas)',
      'Financeiro - Honorários',
      'Financeiro - Custas',
      'Relatórios e produtividade',
      'Biblioteca jurídica',
      'Painel Admin - Equipe',
      'Painel Admin - Configurações',
    ],
    suggestedFeatures: [
      'Alertas de prazos fatais',
      'Integração com tribunais',
      'Assinatura digital de documentos',
      'Timesheet automático',
      'Controle de honorários e custas',
      'Portal do cliente',
      'Templates de peças jurídicas',
      'Pesquisa jurisprudencial com IA',
      'Distribuição automática de processos',
      'Controle de prescrição',
      'Relatórios de produtividade',
      'Chat interno seguro',
    ],
    coreFeatures: [
      'Cadastro de processos',
      'Controle de prazos',
      'Gestão de documentos',
      'Agenda jurídica',
      'Timesheet',
      'Financeiro',
      'Portal do cliente',
      'Relatórios',
    ],
    integrations: [
      'Tribunais (TJSP, STJ, etc.)',
      'Assinatura digital (ICP-Brasil)',
      'Google Calendar',
      'Plataformas de peticionamento',
    ],
    userFlows: [
      'Novo processo → Cadastra → Define prazos → Trabalha → Registra horas → Comunica cliente → Encerra → Fatura',
      'Prazo chegando → Alerta → Advogado atua → Registra andamento → Cliente é notificado',
    ],
    suggestedColors: {
      primary: '#1e293b',
      secondary: '#475569',
      accent: '#64748b',
      background: '#f8fafc',
    },
    designStyle: 'corporate',
    iconStyle: 'lucide',
  },
  {
    id: 'beauty',
    name: 'Salão de Beleza',
    niche: 'Beleza',
    icon: 'Sparkles',
    description: 'Agendamento e gestão completa para salões de beleza, estúdios de estética e SPAs',
    defaultAppName: 'BeautyBook',
    targetAudience: 'Donos de salões de beleza, estúdios de estética, SPAs e profissionais autônomos (manicures, cabeleireiras) que precisam gerenciar agendamentos, profissionais, comissões e fidelizar clientes',
    mainTask: 'Permitir que clientes agendem diversos serviços de beleza (cabelo, unhas, estética, massagem) com profissionais específicos, visualizem portfólio de trabalhos, paguem online ou no local, e acumulem pontos de fidelidade. Para o salão, gerenciar agenda de múltiplos profissionais, controlar comissões, e ter visão do faturamento por serviço e profissional',
    mainBenefit: 'Agenda sempre organizada sem WhatsApp, reduzir faltas com lembretes e cobrança de sinal, aumentar retorno de clientes com programa de fidelidade, e ter controle financeiro com comissões automáticas por profissional',
    dailyUsers: 'Clientes agendando serviços de beleza, profissionais (cabeleireiros, manicures, esteticistas) visualizando sua agenda, recepcionistas conferindo chegadas, e gestores analisando produtividade',
    businessModel: 'Serviços de beleza com comissão por profissional. Venda de produtos. Pacotes de serviços com desconto. Programa de fidelidade',
    mainProblem: 'Salões perdem tempo gerenciando WhatsApp, não sabem a produtividade de cada profissional, têm dificuldade em calcular comissões, e não fidelizam clientes de forma sistemática',
    expectedOutcome: 'Dashboard com agenda do dia por profissional, faturamento, comissões a pagar, clientes que não voltam há X dias, e serviços mais vendidos',
    defaultPages: [
      'Página inicial com serviços',
      'Catálogo de serviços e preços',
      'Nossos profissionais',
      'Galeria de trabalhos',
      'Agendamento inteligente',
      'Meus Agendamentos',
      'Programa de fidelidade',
      'Perfil da cliente',
      'Loja de produtos',
      'Painel Profissional - Minha Agenda',
      'Painel Admin - Dashboard',
      'Painel Admin - Comissões',
      'Painel Admin - Serviços',
      'Painel Admin - Relatórios',
    ],
    suggestedFeatures: [
      'Portfólio de trabalhos',
      'Pacotes de serviços',
      'Programa de indicação',
      'Lembretes por WhatsApp',
      'Controle de comissões automático',
      'Estoque de produtos',
      'Venda de produtos',
      'Planos de fidelidade',
      'Agendamento recorrente',
      'Check-in via QR Code',
      'Avaliações por serviço',
      'Sugestão de retorno',
    ],
    coreFeatures: [
      'Agendamento de múltiplos serviços',
      'Gestão de profissionais',
      'Controle de comissões',
      'Lembretes automáticos',
      'Programa de fidelidade',
      'Galeria de trabalhos',
      'Venda de produtos',
      'Relatórios financeiros',
    ],
    integrations: [
      'WhatsApp para lembretes',
      'Gateway de pagamento',
      'Google Calendar',
      'Instagram (galeria)',
    ],
    userFlows: [
      'Cliente agenda → Escolhe profissional → Seleciona horário → Paga sinal → Recebe lembrete → Vai ao salão → Avalia → Ganha pontos',
      'Admin vê agenda → Profissional atende → Sistema calcula comissão → Pagamento no fim do mês',
    ],
    suggestedColors: {
      primary: '#ec4899',
      secondary: '#f472b6',
      accent: '#fb7185',
      background: '#fdf2f8',
    },
    designStyle: 'modern',
    iconStyle: 'phosphor',
  },
  {
    id: 'contractor',
    name: 'Prestador de Serviços',
    niche: 'Serviços',
    icon: 'Wrench',
    description: 'Gestão de orçamentos, serviços e clientes para prestadores de serviços gerais',
    defaultAppName: 'ServiçoPro',
    targetAudience: 'Eletricistas, encanadores, pintores, técnicos de ar-condicionado, maridos de aluguel e outros prestadores de serviços que precisam profissionalizar orçamentos, gerenciar agenda e fidelizar clientes',
    mainTask: 'Permitir que clientes solicitem orçamentos informando o problema (com fotos), recebam respostas rápidas dos profissionais, acompanhem a execução do serviço, e avaliem ao final. Para o prestador, gerenciar todos os orçamentos e serviços, ter agenda organizada, registrar fotos de antes/depois, e controlar recebimentos',
    mainBenefit: 'Profissionalizar o negócio com orçamentos digitais, aumentar taxa de fechamento com respostas rápidas, construir reputação com avaliações e portfólio, e ter controle financeiro do negócio',
    dailyUsers: 'Clientes solicitando serviços e orçamentos, prestadores respondendo e executando serviços, equipe de apoio (ajudantes), e gestores analisando produtividade (para empresas)',
    businessModel: 'Cobrança por serviço executado. Visita técnica cobrada ou grátis. Contratos de manutenção recorrente. Garantia de serviço',
    mainProblem: 'Prestadores perdem orçamentos por demora, não têm registro de trabalhos anteriores, não conseguem provar qualidade, e não têm controle financeiro',
    expectedOutcome: 'Dashboard com orçamentos pendentes, serviços agendados, a receber, avaliação média, e serviços por tipo',
    defaultPages: [
      'Página inicial do prestador',
      'Solicitar orçamento',
      'Catálogo de serviços',
      'Meus orçamentos recebidos',
      'Acompanhar serviço',
      'Histórico de serviços',
      'Avaliações recebidas',
      'Perfil do cliente',
      'Painel Prestador - Orçamentos',
      'Painel Prestador - Agenda',
      'Painel Prestador - Financeiro',
      'Painel Prestador - Portfólio',
      'Painel Admin - Dashboard',
      'Painel Admin - Equipe',
    ],
    suggestedFeatures: [
      'Orçamento automático por serviço',
      'Fotos de antes e depois',
      'GPS de localização do profissional',
      'Chat cliente-prestador',
      'Garantia de serviço',
      'Múltiplos orçamentos para cliente',
      'Serviços recorrentes (manutenção)',
      'Nota fiscal integrada',
      'Controle de materiais',
      'Agenda inteligente',
      'Avaliações verificadas',
      'Portfólio de trabalhos',
    ],
    coreFeatures: [
      'Solicitação de orçamento',
      'Gestão de orçamentos',
      'Agenda de serviços',
      'Registro fotográfico',
      'Avaliações de clientes',
      'Controle financeiro',
      'Chat integrado',
      'Portfólio digital',
    ],
    integrations: [
      'WhatsApp para comunicação',
      'Gateway de pagamento',
      'Google Maps para localização',
      'Sistema de NF-e',
    ],
    userFlows: [
      'Cliente descreve problema → Envia fotos → Recebe orçamentos → Aceita um → Agenda → Serviço executado → Paga → Avalia',
      'Prestador recebe solicitação → Analisa → Envia orçamento → Cliente aceita → Executa → Registra fotos → Recebe',
    ],
    suggestedColors: {
      primary: '#2563eb',
      secondary: '#3b82f6',
      accent: '#60a5fa',
      background: '#eff6ff',
    },
    designStyle: 'minimal',
    iconStyle: 'heroicons',
  },
];
